# Build 
markdown: kramdown
remote_theme: fongandrew/hydeout

# Setup
title:            Yulim Lee
tagline:          ?testing? # i have no idea where this pops up
description:      Mechanical Engineering Graduate from University of Toronto.

paginate:         5

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  
sidebar_home_link:  true  #this creates a HOME sidebar link that goes back to the main/home page aka Index

#sidebar icon links. checkout _includes/custom_nav_bar_icons or something of that name 
github_username: 96yrlee
linkedin_username: yulim-lee-24b227131





